apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kiwi-role-dev
  namespace: dev
rules:
  - apiGroups:
    - "apps"
    resources: 
      - "pods"
      - "deployments"
      - "services"
      - "secrets"
    verbs: 
      - "create"
      - "get"
      - "list"
      - "update"
      - "patch"
      - "delete"
