apiVersion: v1
kind: Service
metadata:
  name: kiwi-mysql-dev-service
  namespace: dev 
spec:
  selector:
    app: kiwi-mysql-dev
  ports:
    - protocol: TCP
      port: 3306 
      targetPort: 3306
  clusterIP: None 