name: kiwi-prod
services:
  db:
    image: mysql:8
    container_name: drobledo-kiwi-mysql-prod
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: drobledo-kiwi-backend-prod
    depends_on:
      - db
    env_file:
      - ./backend/.env.prod
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: drobledo-kiwi-frontend-prod
    depends_on:
      - backend
    env_file:
      - ./frontend/.env.prod
    ports:
      - "80:80"
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
