name: kiwi-dev
services:
  db:
    image: mysql:8
    container_name: drobledo-kiwi-mysql-dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: drobledo-kiwi-backend-dev
    depends_on:
      - db
    env_file:
      - ./backend/.env.dev
    ports:
      - "8080:8080"
      - "5005:5005"
    networks:
      - app-network

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: drobledo-kiwi-frontend-dev
    depends_on:
      - backend
    env_file:
      - ./frontend/.env.dev
    ports:
      - "5173:5173"
      - "9222:9222"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHROME_REMOTE_DEBUGGING_PORT=9222
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
