#!/usr/bin/bash

cat <<EOF > /docker-entrypoint-initdb.d/init-db.sql
CREATE DATABASE IF NOT EXISTS ${MYSQL_DATABASE};

USE ${MYSQL_DATABASE};

CREATE TABLE IF NOT EXISTS ${MYSQL_INIT_TABLE} (
    id INT PRIMARY KEY,
    message VARCHAR(255)
);

INSERT INTO ${MYSQL_INIT_TABLE} (id, message)
SELECT 1, 'Hello World!'
WHERE NOT EXISTS (SELECT 1 FROM ${MYSQL_INIT_TABLE} WHERE id = 1);

CREATE USER '${BACKEND_DB_USERNAME}'@'%' IDENTIFIED BY '${BACKEND_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON ${MYSQL_DATABASE}.* TO '${BACKEND_DB_USERNAME}'@'%';

CREATE ROLE '${TEAM_ROLE}';
GRANT SELECT, INSERT ON ${MYSQL_DATABASE}.* TO '${TEAM_ROLE}';

CREATE USER '${TEAM_01_USERNAME}'@'%' IDENTIFIED BY '${TEAM_01_PASSWORD}';
CREATE USER '${TEAM_02_USERNAME}'@'%' IDENTIFIED BY '${TEAM_02_PASSWORD}';
CREATE USER '${TEAM_03_USERNAME}'@'%' IDENTIFIED BY '${TEAM_03_PASSWORD}';

GRANT ${TEAM_ROLE} TO '${TEAM_01_USERNAME}'@'%';
GRANT ${TEAM_ROLE} TO '${TEAM_02_USERNAME}'@'%';
GRANT ${TEAM_ROLE} TO '${TEAM_03_USERNAME}'@'%';

FLUSH PRIVILEGES;

EOF