apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: dev 
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: danielrobledo/kiwi-project:backend-dev-latest
        ports:
        - containerPort: 8080
        env:
        - name: BACKEND_DB_URL
          valueFrom:
            secretKeyRef:
              name: backend-secret  
              key: BACKEND_DB_URL_K8S
        - name: BACKEND_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: BACKEND_DB_USERNAME
        - name: BACKEND_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: BACKEND_DB_PASSWORD
      imagePullSecrets:
        - name: dockerhub-secret
