apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiwi-mysql-dev
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kiwi-mysql-dev
  template:
    metadata:
      labels:
        app: kiwi-mysql-dev
    spec:
      containers:
      - name: kiwi-mysql-dev
        image: mysql:8.0 
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-db-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-db-secret
              key: MYSQL_DATABASE
        ports:
        - containerPort: 3306
