package com.drobledo.kiwi;

import com.drobledo.kiwi.model.SavedJob;
import com.drobledo.kiwi.repository.SavedJobRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit.jupiter.SpringExtension;

import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest
public class SavedJobRepositoryTest {

    @Autowired
    private SavedJobRepository savedJobRepository;

    private SavedJob savedJob;

    @BeforeEach
    public void setup() {
        savedJob = new SavedJob();
        savedJob.setTitle("Software Developer");
        savedJob.setCompany("Kiwi Inc.");
    }

    @Test
    public void testSaveJob() {
        // Save a job to the repository
        SavedJob saved = savedJobRepository.save(savedJob);

        // Verify that the saved job has an ID (generated by the database)
        assertNotNull(saved.getId());
    }

    @Test
    public void testFindJobById() {
        // Save a job and retrieve it
        SavedJob saved = savedJobRepository.save(savedJob);
        SavedJob found = savedJobRepository.findById(saved.getId()).orElse(null);

        assertNotNull(found);
        assertEquals(saved.getTitle(), found.getTitle());
        assertEquals(saved.getCompany(), found.getCompany());
    }
}
