name: MySQL CD (Dev)
  
on:
  push:
    branches:
      - develop
      - feature/ci-cd
    paths:
      - '.github/workflows/dev-mysql-workflow.yml'
      - 'k8s/dev/dev-mysql-deployment.yml'
      - 'k8s/dev/dev-mysql-service.yml'
  pull_request:
    branches:
      - develop
      - feature/ci-cd
    paths:
      - '.github/workflows/dev-mysql-workflow.yml'
      - 'k8s/dev/dev-mysql-deployment.yml'
      - 'k8s/dev/dev-mysql-service.yml'

jobs:
  mysql-cd:
    name: Deploy MySQL (Dev)
    runs-on: ubuntu-latest

    environment:
      name: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Kubeconfig
        run: |
            mkdir -p ~/.kube
            echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config

      - name: Create Kubernetes secrets for credentials
        run: |
          kubectl create secret generic mysql-secret \
            --from-literal=MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }} \
            --from-literal=MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }} \
            --namespace=dev \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/dev/dev-mysql-deployment.yaml
          kubectl apply -f k8s/dev/dev-mysql-service.yaml
